docker:
  image: mostalive/ubuntu-14.04-oracle-jdk8
install: |-
  sudo apt-get purge maven maven2 maven3
  sudo apt-add-repository ppa:andrei-pozolotin/maven3
  sudo apt-get update
  sudo apt-get install -y maven3 git
architect:
- jachinte
decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  pubring.gpg: "repo/.rultor/pubring.gpg.asc"
  secring.gpg: "repo/.rultor/secring.gpg.asc"
env:
  MAVEN_OPTS: "-Xmx512m -XX:MaxPermSize=256m"
release:
  script: |
    mvn org.eclipse.tycho:tycho-versions-plugin:set-version "-DnewVersion=${tag}"
    mvn clean deploy -PAmelia --settings /home/r/settings.xml
    git commit -am "${tag}"
    git push
merge:
  script: |
    mvn clean install
deploy:
  script: |
    mvn clean deploy -PAmelia --settings /home/r/settings.xml
